version: "3.7"
services:
  api:
    build: .
    tty: true
    ports:
    - 8080:8080

  mariadb:
    image: mariadb
    restart: always
    ports:
    - 3306:3306
    environment:
     - MYSQL_ROOT_USER=root
     - MARIADB_ROOT_PASSWORD=password
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=deliveries